### ISSUE TITLE
Req update 3.9

### ISSUE THREAD

**Issue by anarki-install** [dtz-aditia/Comz3#3]
Update enc python nya dong min, thnks 👋

**Comment by dtz-aditia** [comment]
> Update enc python nya dong min, thnks 👋

Udah agak males bikin kaya gituan gan ,selalu aja ketembus... , klo kamu user py3 ,pke aja compiler bawaan python nya ... itu udah lumayan greget krna udah di update bareng sama versi py nya...

**Comment by anarki-install** [comment]
ok min
